### ISSUE TITLE
Theme suggestion | Python

### ISSUE THREAD

**Issue by AlexFlipnote** [Nikki1993/google-dark-syntax#2]
Not sure if this is the right spot to suggest something, but is it possible to add a colour to async def like the normal def? (The definition name, as in example: **something**)

Language: Python

![Image](https://i.alexflipnote.xyz/cfd05d.png)

**Comment by Nikki1993** [comment]
Hey,

I haven't been using Atom for a while now, switched to VSCode, but I can take a look over weekend and add support for async keyword over weekend :)

**Comment by AlexFlipnote** [comment]
Hmm, could possibly look into it too and make a PR if I would solve this.
Because your theme is what I love the most out of all, still use it today you know :P

**Comment by Nikki1993** [comment]
@AlexFlipnote cheers :) I will pay more attention to the theme then. I am currently using vscode so I should find some time to port it to both :) 

PR is always welcome, I am experimenting with atom/vscode themeing myself.

**Comment by AlexFlipnote** [comment]
Hello, long time since I have been checking by here.
I have noticed that Atom has updated itself considering that this repo hasn't changed anything yet, so the issue I noted before is solved, thank you for a great theme still :)

![Image](https://i.alexflipnote.xyz/b57c9b.png)
